# Name of the workflow shown in the GitHub Actions tab
name: CI


# Define when this workflow should automatically run
on:

  # Run workflow whenever code is pushed to the main branch
  push:
    branches: ["main"]

  # Also run workflow whenever a pull request targets main
  pull_request:
    branches: ["main"]


# Define the jobs/tasks for this workflow
jobs:

  # Name of the job
  test-and-build:

    # Operating system for the temporary GitHub virtual machine
    runs-on: ubuntu-latest


    # Ordered list of steps the VM will execute
    steps:

      # Step 1:
      # Download/copy the repository code into the VM
      - name: Checkout code
        uses: actions/checkout@v4


      # Step 2:
      # Install Python onto the VM
      - name: Set up Python
        uses: actions/setup-python@v5

        # Configuration settings for the Python setup action
        with:

          # Specify Python version
          python-version: "3.11"


      # Step 3:
      # Install project dependencies
      - name: Install dependencies

        # Run shell commands inside the VM
        run: |

          # Upgrade pip installer
          python -m pip install --upgrade pip

          # Install all packages from requirements.txt
          pip install -r requirements.txt


      # Step 4:
      # Run automated tests using pytest
      - name: Run tests
        run: python -m pytest


      # Step 5:
      # Build the Docker image to verify the container works
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-cicd-api:latest